configfile: "config.yaml"


rule all:
    input:
        expand("output/hifi/{cell_line}_{platform}_new_interface", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']),
        "output/ont/COLO829_ont1_new_interface",
        #bar_pdf_bw2 = "tnpair/Fig5_v5.pdf",
        #bar_pdf_bw3 = "tnpair/Fig5_v5_ls.pdf"
        bar_pdf_bw = "tnpair/Fig5_v5_lgs.pdf",
        bar_pdf2_bw  = "sv_num_with_asmcount_filter_bar2_bw.pdf",
        bar_pdf_bw_lg = "tnpair/Fig5_v5_bw.pdf",
        bar_pdf_bw_ls = "tnpair/Fig5_v5_ls_bw.pdf"

rule evaluate:
    input:
        snf = "../../1a.alignment_sv_tools/output/sniffles_latest/{cell_line}_{platform}/grch38_multi.vcf.gz",
        severus = "../../1a.alignment_sv_tools/output/severus_latest/{cell_line}_{platform}/grch38_cutoff2_read_ids/somatic_SVs/severus_somatic.vcf",
        severus_id = "../../1a.alignment_sv_tools/output/severus_latest/{cell_line}_{platform}/grch38_cutoff2_read_ids/read_ids.csv",
        savana = "../../1a.alignment_sv_tools/output/savana13/{cell_line}_{platform}/grch38/grch38_T_tag.classified.somatic.vcf",
        savana_id = "../../1a.alignment_sv_tools/output/savana13/{cell_line}_{platform}/grch38/grch38_T_tag.sv_breakpoints_read_support.tsv",
        nanomonsv = "../../1a.alignment_sv_tools/output/nanomonsv_latest/{cell_line}_{platform}/grch38_tnpair.vcf",
        nanomonsv_id = "../../1a.alignment_sv_tools/output/nanomonsv_latest/{cell_line}_{platform}/T/grch38_parse.nanomonsv.supporting_read.txt",

        cram = "../../1a.alignment_sv_tools/output/align/{cell_line}_{platform}/T/grch38.cram",
        conf_bed = "/hlilab/alvin/pangenome_sv_benchmarking/minisv/data/hs38.reg.bed"
    output:
        folder = directory("output/hifi/{cell_line}_{platform}_new_interface"),
        snf_somatic = "output/hifi/{cell_line}_{platform}_snf_somatic.vcf"
    conda: "msvpy"
    params:
        platform = lambda wildcards: 'hifi' if 'hifi' in wildcards.platform else 'ont'
    shell:
        """
        minisv snfpair -n 2 -t 1 {input.snf}  > {output.snf_somatic}

        minisv sv-cross-ref-filter --maskb /hlilab/alvin/pangenome_sv_benchmarking/minisv/data/hg38.cen-mask.bed --mm2 ../../1a.alignment_sv_tools/minimap2/minimap2 --mg ../../1a.alignment_sv_tools/minigraph/minigraph -p {params.platform} -b {input.conf_bed} --vcf {input.severus} {input.savana} {input.nanomonsv} {output.snf_somatic} --readid_tsv {input.severus_id} {input.savana_id} {input.nanomonsv_id} {output.snf_somatic} {input.cram} ../../1a.alignment_sv_tools/grch38.fa ../../5.assembly_evaluation/{wildcards.cell_line}BL.asm.bp.hap1.fa.gz ../../5.assembly_evaluation/{wildcards.cell_line}BL.asm.bp.hap2.fa.gz /hlilab/hli/minigraph/HPRC-r2/CHM13-464.gfa.gz {output.folder}

        """


rule evaluate2:
    input:
        snf = "../../1a.alignment_sv_tools/output/sniffles_latest/COLO829_ont1/grch38_multi.vcf.gz",
        severus = "../../1a.alignment_sv_tools/output/severus_latest/COLO829_ont1/grch38_cutoff2_read_ids/somatic_SVs/severus_somatic.vcf",
        severus_id = "../../1a.alignment_sv_tools/output/severus_latest/COLO829_ont1/grch38_cutoff2_read_ids/read_ids.csv",
        savana = "../../1a.alignment_sv_tools/output/savana13/COLO829_ont1/grch38/grch38_T_tag.classified.somatic.vcf",
        savana_id = "../../1a.alignment_sv_tools/output/savana13/COLO829_ont1/grch38/grch38_T_tag.sv_breakpoints_read_support.tsv",
        nanomonsv = "../../1a.alignment_sv_tools/output/nanomonsv_latest/COLO829_ont1/grch38_tnpair.vcf",
        nanomonsv_id = "../../1a.alignment_sv_tools/output/nanomonsv_latest/COLO829_ont1/T/grch38_parse.nanomonsv.supporting_read.txt",

        cram = "../../1a.alignment_sv_tools/output/align/COLO829_ont1/T/grch38.cram",
        conf_bed = "/hlilab/alvin/pangenome_sv_benchmarking/minisv/data/hs38.reg.bed"
    output:
        folder = directory("output/ont/COLO829_ont1_new_interface"),
        snf_somatic = "output/COLO829_ont1_snf_somatic.vcf"
    conda: "msvpy"
    params:
        platform = "ont"
    shell:
        """
        minisv snfpair -n 2 -t 1 {input.snf}  > {output.snf_somatic}

        minisv sv-cross-ref-filter  --maskb /hlilab/alvin/pangenome_sv_benchmarking/minisv/data/hg38.cen-mask.bed --mm2 ../../1a.alignment_sv_tools/minimap2/minimap2 --mg ../../1a.alignment_sv_tools/minigraph/minigraph -p {params.platform} -b {input.conf_bed} --vcf {input.severus} {input.savana} {input.nanomonsv} {output.snf_somatic} --readid_tsv {input.severus_id} {input.savana_id} {input.nanomonsv_id} {output.snf_somatic} {input.cram} ../../1a.alignment_sv_tools/grch38.fa ../../20.ont_assembly/COLO829BL_ont1.asm.bp.hap1.fa.gz ../../20.ont_assembly/COLO829BL_ont1.asm.bp.hap2.fa.gz /hlilab/hli/minigraph/HPRC-r2/CHM13-464.gfa.gz {output.folder}

        """

# consensus version
rule othercellline_tnpair_upset_ls:
    input:
        union_count     = expand("output/hifi/{cell_line}_hifi1_new_interface/l_only_union_stat.msv", cell_line=['COLO829', 'HCC1395', 'HCC1937', 'HCC1954', 'NCI1437', 'NCI2009']),
        asm_union_count = expand("output/hifi/{cell_line}_hifi1_new_interface/l+s_union_stat.msv", cell_line=['COLO829', 'HCC1395', 'HCC1937', 'HCC1954', 'NCI1437', 'NCI2009'])
    output:
        stat = "tnpair/Fig5_v5_stat_ls.tsv",
        #metrics = "tnpair/Fig5_v5_metrics_ls.tsv",
        #bar_pdf = "tnpair/Fig5_v5_0_ls.pdf",
        bar_pdf_bw = "tnpair/Fig5_v5_ls_bw.pdf"
    conda: "plot"
    script:
        "scripts/Fig5_v4_subv0_grouped_somatic_sv_fp_fn_colo829_barchart_3callers.R"

# consensus version
rule othercellline_tnpair_upset_lg:
    input:
        union_count     = expand("output/hifi/{cell_line}_hifi1_new_interface/l_only_union_stat.msv", cell_line=['COLO829', 'HCC1395', 'HCC1937', 'HCC1954', 'NCI1437', 'NCI2009']),
        asm_union_count = expand("output/hifi/{cell_line}_hifi1_new_interface/l+g_union_stat.msv", cell_line=['COLO829', 'HCC1395', 'HCC1937', 'HCC1954', 'NCI1437', 'NCI2009'])
    output:
        stat = "tnpair/Fig5_v5_stat.tsv",
        #metrics = "tnpair/Fig5_v5_metrics.tsv",
        #bar_pdf = "tnpair/Fig5_v5_0.pdf",
        bar_pdf_bw = "tnpair/Fig5_v5_bw.pdf"
    conda: "plot"
    script:
        "scripts/Fig5_v4_subv0_grouped_somatic_sv_fp_fn_colo829_barchart_3callers.R"

# consensus version
rule othercellline_tnpair_upset_lg_and_s:
    input:
        union_count     = expand("output/hifi/{cell_line}_hifi1_new_interface/l_only_union_stat.msv", cell_line=['COLO829', 'HCC1395', 'HCC1937', 'HCC1954', 'NCI1437', 'NCI2009']),
        g_union_count = expand("output/hifi/{cell_line}_hifi1_new_interface/l+g_union_stat.msv", cell_line=['COLO829', 'HCC1395', 'HCC1937', 'HCC1954', 'NCI1437', 'NCI2009']),
        gs_union_count = expand("output/hifi/{cell_line}_hifi1_new_interface/l+g+s_union_stat.msv", cell_line=['COLO829', 'HCC1395', 'HCC1937', 'HCC1954', 'NCI1437', 'NCI2009'])
    output:
        stat = "tnpair/Fig5_v5_stat_lgs.tsv",
        #metrics = "tnpair/Fig5_v5_metrics_lgs.tsv",
        bar_pdf = "tnpair/Fig5_v5_0_lgs.pdf",
        bar_pdf_bw = "tnpair/Fig5_v5_lgs.pdf"
    conda: "plot"
    script:
        "scripts/Fig5_v5_3callers.R"



#rule sv_num_with_asmcount_filter:
#    input:
#        severus_stat = expand("../10.mixed_assembly_10percent_latest/output/minisv_puretumor_somatic_asm/severus_{cell_line}_hifi1_somatic_generation2_filterasm.stat", cell_line=['COLO829', 'NCI2009','HCC1395', 'HCC1937', 'HCC1954', 'NCI1437']),
#        snf_stat     = expand("../10.mixed_assembly_10percent_latest/output/minisv_puretumor_somatic_asm/snf_{cell_line}_hifi1_somatic_generation2_filterasm.stat",     cell_line=['COLO829', 'NCI2009','HCC1395', 'HCC1937', 'HCC1954', 'NCI1437']),
#        nano_stat = expand("../10.mixed_assembly_10percent_latest/output/minisv_puretumor_somatic_asm/nanomonsv_{cell_line}_hifi1_somatic_generation2_filterasm.stat", cell_line=['COLO829', 'NCI2009','HCC1395', 'HCC1937', 'HCC1954', 'NCI1437']),
#        savana_stat = expand("../10.mixed_assembly_10percent_latest/output/minisv_puretumor_somatic_asm/savana_{cell_line}_hifi1_somatic_generation2_filterasm.stat", cell_line=['COLO829', 'NCI2009','HCC1395', 'HCC1937', 'HCC1954', 'NCI1437'])
#    output:
#        stat = "sv_num_with_asmcount_filter.tsv",
#        stat_sv_num = "sv_num_with_asmcount_filter_summarize.tsv",
#        bar_pdf  = "sv_num_with_asmcount_filter_bar.pdf",
#        bar_pdf2  = "sv_num_with_asmcount_filter_bar2.pdf",
#        bar_pdf2_bw  = "sv_num_with_asmcount_filter_bar2_bw.pdf"
#    conda: "plot"
#    script:
#        "scripts/alltools_sv_count_filter_by_asmreads_v5.R"


rule sv_num_with_asmcount_filter:
    input:
        severus_stat = expand("output/hifi/{cell_line}_hifi1_new_interface/severus_l+s_3_filtered.stat", cell_line=['COLO829', 'NCI2009','HCC1395', 'HCC1937', 'HCC1954', 'NCI1437']),
        snf_stat     = expand("output/hifi/{cell_line}_hifi1_new_interface/sniffles2_l+s_3_filtered.stat", cell_line=['COLO829', 'NCI2009','HCC1395', 'HCC1937', 'HCC1954', 'NCI1437']),
        nano_stat = expand("output/hifi/{cell_line}_hifi1_new_interface/nanomonsv_l+s_3_filtered.stat", cell_line=['COLO829', 'NCI2009','HCC1395', 'HCC1937', 'HCC1954', 'NCI1437']),
        savana_stat = expand("output/hifi/{cell_line}_hifi1_new_interface/savana_l+s_3_filtered.stat", cell_line=['COLO829', 'NCI2009','HCC1395', 'HCC1937', 'HCC1954', 'NCI1437'])
    output:
        stat = "sv_num_with_asmcount_filter.tsv",
        stat_sv_num = "sv_num_with_asmcount_filter_summarize.tsv",
        bar_pdf  = "sv_num_with_asmcount_filter_bar.pdf",
        bar_pdf2  = "sv_num_with_asmcount_filter_bar2.pdf",
        bar_pdf2_bw  = "sv_num_with_asmcount_filter_bar2_bw.pdf"
    conda: "plot"
    script:
        "scripts/alltools_sv_count_filter_by_asmreads_v5.R"
