configfile: "config.yaml"


rule all:
    input:
        expand("output/{cell_line}_{platform}_new_interface", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']),
        "output/ont/COLO829_ont1_new_interface"


rule evaluate:
    input:
        severus = "../../1a.alignment_sv_tools/output/severus_latest/{cell_line}_{platform}/grch38_cutoff2_read_ids/somatic_SVs/severus_somatic.vcf",
        severus_id = "../../1a.alignment_sv_tools/output/severus_latest/{cell_line}_{platform}/grch38_cutoff2_read_ids/read_ids.csv",
        savana = "../../1a.alignment_sv_tools/output/savana13/{cell_line}_{platform}/grch38/grch38_T_tag.classified.somatic.vcf",
        savana_id = "../../1a.alignment_sv_tools/output/savana13/{cell_line}_{platform}/grch38/grch38_T_tag.sv_breakpoints_read_support.tsv",
        nanomonsv = "../../1a.alignment_sv_tools/output/nanomonsv_latest/{cell_line}_{platform}/grch38_tnpair.vcf",
        nanomonsv_id = "../../1a.alignment_sv_tools/output/nanomonsv_latest/{cell_line}_{platform}/T/grch38_parse.nanomonsv.supporting_read.txt",

        cram = "../../1a.alignment_sv_tools/output/align/{cell_line}_{platform}/T/grch38.cram",
        conf_bed = "/hlilab/alvin/pangenome_sv_benchmarking/minisv/data/hs38.reg.bed"
    output:
        folder = directory("output/{cell_line}_{platform}_new_interface")
    conda: "msvpy"
    params:
        platform = lambda wildcards: 'hifi' if 'hifi' in wildcards.platform else 'ont'
    shell:
        """

        minisv denovo-filterasm -p {params.platform} -b {input.conf_bed} {input.severus} {input.savana} {input.nanomonsv} {input.severus_id} {input.savana_id} {input.nanomonsv_id} {input.cram} ../../1a.alignment_sv_tools/grch38.fa ../../5.assembly_evaluation/{wildcards.cell_line}BL.asm.bp.hap1.fa.gz ../../5.assembly_evaluation/{wildcards.cell_line}BL.asm.bp.hap2.fa.gz /hlilab/hli/minigraph/HPRC-r2/CHM13-464.gfa.gz {output.folder}

        """


rule evaluate2:
    input:
        severus = "../../1a.alignment_sv_tools/output/severus_latest/COLO829_ont1/grch38_cutoff2_read_ids/somatic_SVs/severus_somatic.vcf",
        severus_id = "../../1a.alignment_sv_tools/output/severus_latest/COLO829_ont1/grch38_cutoff2_read_ids/read_ids.csv",
        savana = "../../1a.alignment_sv_tools/output/savana13/COLO829_ont1/grch38/grch38_T_tag.classified.somatic.vcf",
        savana_id = "../../1a.alignment_sv_tools/output/savana13/COLO829_ont1/grch38/grch38_T_tag.sv_breakpoints_read_support.tsv",
        nanomonsv = "../../1a.alignment_sv_tools/output/nanomonsv_latest/COLO829_ont1/grch38_tnpair.vcf",
        nanomonsv_id = "../../1a.alignment_sv_tools/output/nanomonsv_latest/COLO829_ont1/T/grch38_parse.nanomonsv.supporting_read.txt",

        cram = "../../1a.alignment_sv_tools/output/align/COLO829_ont1/T/grch38.cram",
        conf_bed = "/hlilab/alvin/pangenome_sv_benchmarking/minisv/data/hs38.reg.bed"
    output:
        folder = directory("output/ont/COLO829_ont1_new_interface")
    conda: "msvpy"
    params:
        platform = "ont"
    shell:
        """

        minisv denovo-filterasm -p {params.platform} -b {input.conf_bed} {input.severus} {input.savana} {input.nanomonsv} {input.severus_id} {input.savana_id} {input.nanomonsv_id} {input.cram} ../../1a.alignment_sv_tools/grch38.fa ../../20.ont_assembly/COLO829BL_ont1.asm.bp.hap1.fa.gz ../../20.ont_assembly/COLO829BL_ont1.asm.bp.hap2.fa.gz /hlilab/hli/minigraph/HPRC-r2/CHM13-464.gfa.gz {output.folder}

        """

#### ../../20.ont_assembly/COLO829BL_ont1.asm.bp.hap1.fa.gz ../../20.ont_assembly/COLO829BL_ont1.asm.bp.hap2.fa.gz
