import os
import glob

wildcard_constraints:
    cell_line = "[A-Za-z0-9]+",
    pair = "normal|tumor|T|BL",
    assembly = "chm13|grch38",
    platform = "ont1|ont2|hifi1"

assembly  = ['grch38', 'chm13']
celllines = ["COLO829"]


rule gfa2fa:
    input:
         "{cell_line}{pair}_{platform}.asm.bp.hap{hap}.p_ctg.gfa"
    output:
         "{cell_line}{pair}_{platform}.asm.bp.hap{hap}.fa.gz"
    shell:
         """
         ../5.assembly_evaluation/gfatools/gfatools gfa2fa {input} | bgzip -c - > {output}
         """


module aligner_workflow:
    snakefile: "rules/minimap2.smk"
    config: config

use rule * from aligner_workflow as minimap2_workflow_*
include: "rules/sniffles2.smk"

include: "rules/sniffles2_latest.smk"

include: "rules/clair3.smk"
module severus_workflow:
    snakefile: "rules/severus.smk"
    config: config
use rule * from severus_workflow as severus_workflow_*

module severus_workflow_latest:
    snakefile: "rules/severus_latest.smk"
    config: config
use rule * from severus_workflow_latest as latest_severus_workflow_*

include: "rules/savana1.2.smk"
include: "rules/savana1.36.smk"
include: "rules/nanomonsv.smk"
include: "rules/nanomonsv_latest.smk"

include: "rules/gafcall_tnpair.smk"

#sniffles_files  = expand(expand("output/sniffles/{cell_line}_{platform}/{{pair}}/{{assembly}}.vcf.gz", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), pair=["T", "BL"], assembly=config['assembly'])
#sniffles_tbi_files  = expand(expand("output/sniffles/{cell_line}_{platform}/{{pair}}/{{assembly}}.vcf.gz.tbi", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), pair=["T", "BL"], assembly=config['assembly'])
#sniffles_mosaic_files  = expand(expand("output/sniffles_mosaic/{cell_line}_{platform}/{{pair}}/{{assembly}}.vcf.gz", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), pair=["T", "BL"], assembly=config['assembly'])
#sniffles_mosaic_tbi_files  = expand(expand("output/sniffles_mosaic/{cell_line}_{platform}/{{pair}}/{{assembly}}.vcf.gz.tbi", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), pair=["T", "BL"], assembly=config['assembly'])
#sniffles_mix  = expand(expand("output/sniffles_mosaic/{cell_line}_{platform}/{{assembly}}_mixdown_mosaic.vcf.gz", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), assembly=config['assembly'])
#sniffles_mix_tbi  = expand(expand("output/sniffles_mosaic/{cell_line}_{platform}/{{assembly}}_mixdown_mosaic.vcf.gz.tbi", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), assembly=config['assembly'])
#
#sniffles_mo_multi_files  = expand(expand("output/sniffles_mosaic/{cell_line}_{platform}/{{pair}}/{{assembly}}.snf", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), pair=["T", "BL"], assembly=config['assembly'])
#sniffles_mo_multi_vcf_files  = expand(expand("output/sniffles_mosaic/{cell_line}_{platform}/{{assembly}}_multi.vcf.gz", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), assembly=config['assembly'])

#severus_outdir  = expand(expand("output/severus/{cell_line}_{platform}/{{assembly}}", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), assembly=config['assembly'])
#severus_outdir_repeat2  = expand(expand("output/severus/{cell_line}_{platform}/{{assembly}}_repeat2", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), assembly=config['assembly'])
#severus_single_outdir  = expand(expand("output/severus_{platform}/{cell_line}_{{pair}}_{{assembly}}", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), pair=["T", "BL"], assembly=config['assembly'])
#
#
#extract_linear_files  = expand(expand("output/align/{cell_line}_{{pair}}_{platform}_{{assembly}}l.def.gsv.gz", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), pair=["T", "BL"], assembly=config['assembly'])
#extract_graph_files  = expand(expand("output/align/{cell_line}_{{pair}}_{platform}_{{assembly}}g.def.gsv.gz", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), pair=["T", "BL"], assembly=config['assembly'])
#
#svision_outdir  = expand(expand("output/svision/{cell_line}_{platform}/{{assembly}}", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), assembly=config['assembly'])
#svision_vcfs  = expand(expand("output/svision/{cell_line}_{platform}/{{assembly}}/{cell_line}.svision_pro_v1.8.s5.vcf", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), assembly=config['assembly'])
#
#paf_mixed  = expand(expand("output/align/{cell_line}_{platform}/{{assembly}}_mixdown.paf.gz", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), assembly=config['assembly'])
#gaf_mixed  = expand(expand("output/align/{cell_line}_{platform}/{{assembly}}g_mixdown.paf.gz", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), assembly=config['assembly'])
#


#minisv_pair_t2t = expand(expand("output/minisv_pair/{cell_line}_{platform}_pair_chm13l_l+t+g+s_{{cnt}}.msv.gz", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), cnt=['c2s0', 'c3s0', 'c4s0', 'c5s0'])
#minisv_pair_t2t_tg = expand(expand("output/minisv_pair/{cell_line}_{platform}_pair_chm13l_l+t+g_{{cnt}}.msv.gz", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), cnt=['c2s0'])
#
#minisv_pair_t = expand(expand("output/minisv_pair/{cell_line}_{platform}_pair_hg38l_l+t_{{cnt}}.msv.gz", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), cnt=['c2s0', 'c3s0', 'c4s0', 'c5s0'])
#minisv_pair_g = expand(expand("output/minisv_pair/{cell_line}_{platform}_pair_hg38l_l+g_{{cnt}}.msv.gz", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), cnt=['c2s0', 'c3s0', 'c4s0', 'c5s0'])
#minisv_pair_tg = expand(expand("output/minisv_pair/{cell_line}_{platform}_pair_hg38l_l+tg_{{cnt}}.msv.gz", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), cnt=['c2s0', 'c3s0', 'c4s0', 'c5s0'])
#minisv_pair_gx = expand(expand("output/minisv_pair/{cell_line}_{platform}_pair_{{assembly}}g_g+x_{{cnt}}.msv.gz", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), cnt=['c2s0', 'c3s0', 'c4s0', 'c5s0'], assembly=['chm13', 'grch38'])
#minisv_pair_lx = expand(expand("output/minisv_pair/{cell_line}_{platform}_pair_{{assembly}}l_l+x_{{cnt}}.msv.gz", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), cnt=['c2s0', 'c3s0', 'c4s0', 'c5s0'], assembly=['chm13', 'grch38'])
#
#
#minisv_mixed_mosaic_g = expand(expand("output/minisv_mosaic/{cell_line}_{platform}/{{assembly}}g_g+x_mosaic.msv.gz", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), assembly=['chm13', 'grch38'])
#minisv_mixed_mosaic_l = expand(expand("output/minisv_mosaic/{cell_line}_{platform}/{{assembly}}l_l+x_mosaic.msv.gz", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), assembly=['chm13', 'grch38'])
#minisv_mixed_mosaic_lg = expand(expand("output/minisv_mosaic/{cell_line}_{platform}/{{assembly}}l_l+g_mosaic.msv.gz", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), assembly=['chm13', 'grch38'])
#minisv_mixed_mosaic_lt = expand("output/minisv_mosaic/{cell_line}_{platform}/grch38l_l+g_mosaic.msv.gz", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform'])
#minisv_mixed_mosaic_ltg = expand("output/minisv_mosaic/{cell_line}_{platform}/grch38l_l+t+g_mosaic.msv.gz", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform'])
#
#
#minisv_self_extract = expand(expand("output/minisv/{cell_line}_{{pair}}_{platform}_self.rsv.gz", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), pair=["T", "BL"])
#
#minisv_linear_def_extract = expand(expand("output/minisv/{cell_line}_{{pair}}_{platform}_{{assembly}}l.def.rsv.gz", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), pair=["T", "BL"], assembly=['chm13', 'grch38'])
#
#minisv_graph_def_extract = expand(expand("output/minisv/{cell_line}_{{pair}}_{platform}_{{assembly}}g.def.rsv.gz", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), pair=["T", "BL"], assembly=['chm13', 'grch38'])
#
#minisv_single_call = expand(expand("output/minisv/{cell_line}_{{pair}}_{platform}_{{assembly}}l_l+x_merge_{{cnt}}.msv.gz", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), pair=["T", "BL"], assembly=['chm13', 'grch38'], cnt=['c2s0', 'c3s0', 'c4s0', 'c5s0'])
#
#minisv_single_graph_call = expand(expand("output/minisv/{cell_line}_{{pair}}_{platform}_{{assembly}}l_l+g_merge_{{cnt}}.msv.gz", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), pair=["T", "BL"], assembly=['chm13', 'grch38'], cnt=['c2s0', 'c3s0', 'c4s0', 'c5s0'])
#
#minisv_single_s_call = expand(expand("output/minisv/{cell_line}_{{pair}}_{platform}_{{assembly}}l_l+s_merge_{{cnt}}.msv.gz", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), pair=["T", "BL"], assembly=['chm13', 'grch38'], cnt=['c2s0', 'c3s0', 'c4s0', 'c5s0'])
#
#minisv_single_lg_call = expand(expand("output/minisv/{cell_line}_{{pair}}_{platform}_{{assembly}}l_l+g_merge_{{cnt}}.msv.gz", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), pair=["T", "BL"], assembly=['chm13', 'grch38'], cnt=['c2s0', 'c3s0', 'c4s0', 'c5s0'])
#
#minisv_single_ts_call = expand(expand("output/minisv/{cell_line}_{{pair}}_{platform}_grch38l_t+s_merge_{{cnt}}.msv.gz", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), pair=["T", "BL"], assembly=['chm13', 'grch38'], cnt=['c2s0', 'c3s0', 'c4s0', 'c5s0'])
#
#minisv_single_tg_call = expand(expand("output/minisv/{cell_line}_{{pair}}_{platform}_grch38l_t+g_merge_{{cnt}}.msv.gz", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), pair=["T", "BL"], assembly=['chm13', 'grch38'], cnt=['c2s0', 'c3s0', 'c4s0', 'c5s0'])
#
#minisv_single_tgs_call = expand(expand("output/minisv/{cell_line}_{{pair}}_{platform}_grch38l_t+g+s_merge_{{cnt}}.msv.gz", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), pair=["T", "BL"], assembly=['chm13', 'grch38'], cnt=['c2s0', 'c3s0', 'c4s0', 'c5s0'])
#
#tn_eval_length = expand("output/minisv_view/tn_{cell_line}_{platform}_eval_len.tsv", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform'])
#single_eval_length = expand("output/minisv_view/single_{cell_line}_{platform}_eval_len.tsv", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform'])
#mixed_eval_length = expand("output/minisv_view/mixed_{cell_line}_{platform}_merge_eval_len.tsv", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform'])
#
#include: "rules/minisv_eval_all_tools.smk"
#
#
#svision_outdir_somatic = expand(expand("output/svision/{cell_line}_{platform}/somatic/{cell_line}_{{assembly}}_tn.svision_pro_v1.8.s5.somatic_s1.vcf", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), assembly=config['assembly'])
#
#svision_single_vcfs  = expand(expand("output/svision_single/{cell_line}_{platform}_{{pair}}/{{assembly}}/{cell_line}.svision_pro_v1.8.s5.vcf", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), assembly=config['assembly'], pair=['T', 'BL'])
#
## minisv eval files
#minisv_eval_files = expand(expand("output/minisv_eval_tnpair/{cell_line}_{platform}_{{assembly}}_eval_count{{count}}.tsv", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), assembly=['chm13', 'grch38'], count=[2,3,4,5,10])
#minisv_eval_files_M = expand(expand(expand("output/minisv_eval_tnpair_concensus/{cell_line}_{platform}_{{assembly}}_eval_count{{count}}.tsv", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), assembly=['chm13', 'grch38'], count=[2,3,4,5,10]))
#
#single_eval_performance = expand(expand("output/minisv_eval_single{{pair}}/single_{cell_line}_{platform}_{{assembly}}_eval_count{{count}}.tsv", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), pair=['T', 'BL'], assembly=['chm13', 'grch38'], count=[2,3,4,5,10])
#minisv_eval_mixed_files = expand(expand("output/minisv_eval_tnpair/{cell_line}_{platform}_{{assembly}}_eval_mixed.tsv", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), assembly=['chm13', 'grch38'])
#tn_eval_length = expand(expand("output/alltools_view/tn_{cell_line}_{platform}_{{assembly}}_eval_len.tsv", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), assembly=['chm13', 'grch38'])
#pair_eval_single_length = expand(expand("output/minisv_view_single{{pair}}/single_{cell_line}_{platform}_{{assembly}}_eval_len.tsv", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), pair=['T', 'BL'], assembly=['chm13', 'grch38'])


###"{cell_line}{pair}_{platform}.asm.bp.hap{hap}.fa.gz"
genome_fa = expand("{cell_line}{pair}_{platform}.asm.bp.hap{hap}.fa.gz", cell_line=celllines, platform=['ont1', 'ont2'], pair=['BL'], hap=[1, 2])
print(genome_fa)

assembly  = ['grch38']
celllines = ["COLO829"]
platforms = ['ont1', 'ont2']
sniffles_multi_files  = expand(expand("output/sniffles/{cell_line}_{platform}/{{pair}}/{{assembly}}.snf", cell_line=celllines, platform=platforms), pair=["T", "BL"], assembly=assembly)
sniffles_multi_vcf_files  = expand(expand("output/sniffles/{cell_line}_{platform}/{{assembly}}_multi.vcf.gz", cell_line=celllines, platform=platforms), assembly=assembly)

sniffles_multi_files_latest  = expand(expand("output/sniffles_latest/{cell_line}_{platform}/{{pair}}/{{assembly}}.snf", cell_line=celllines, platform=platforms), pair=["T", "BL"], assembly=assembly)
sniffles_multi_vcf_files_latest  = expand(expand("output/sniffles_latest/{cell_line}_{platform}/{{assembly}}_multi.vcf.gz", cell_line=celllines, platform=platforms), assembly=assembly)

clair3_outdir  = expand("output/clair3/{cell_line}_{platform}/{pair}/{assembly}/", cell_line=celllines, platform=platforms, pair=["T", "BL"], assembly=assembly)

savana12_outdir  = expand(expand("output/savana12/{cell_line}_{platform}/{{assembly}}", cell_line=celllines, platform=platforms), assembly=assembly)
savana12_vcf     = expand(expand("output/savana12/{cell_line}_{platform}/{{assembly}}/{{assembly}}_T_tag.classified.somatic.vcf", cell_line=celllines, platform=platforms), assembly=assembly)

savana13_outdir  = expand(expand("output/savana13/{cell_line}_{platform}/{{assembly}}", cell_line=celllines, platform=platforms), assembly=assembly)
savana13_vcf     = expand(expand("output/savana13/{cell_line}_{platform}/{{assembly}}/{{assembly}}_T_tag.classified.somatic.vcf", cell_line=celllines, platform=platforms), assembly=assembly)

nanomonsv_files  = expand("output/nanomonsv/{cell_line}_{platform}/{assembly}_tnpair.txt", cell_line=celllines, assembly=assembly, platform=platforms)
nanomonsv_files_latest  = expand("output/nanomonsv_latest/{cell_line}_{platform}/{assembly}_tnpair.txt", cell_line=celllines, assembly=assembly, platform=platforms)

minisv_pair = expand(expand("output/minisv_pair/{cell_line}_{platform}_pair_hg38l_l+t+g+s_{{cnt}}.msv.gz", cell_line=celllines, platform=platforms), cnt=['c2s1', 'c3s1', 'c4s1', 'c5s1'])
minisv_pair_tg = expand(expand("output/minisv_pair/{cell_line}_{platform}_pair_hg38l_l+tg_{{cnt}}.msv.gz", cell_line=celllines, platform=platforms), cnt=['c2s1', 'c3s1', 'c4s1', 'c5s1'])
minisv_self = expand("output/minisv/{cell_line}_{pair}_{platform}_self.rsv.gz", cell_line=celllines, platform=platforms, pair=['T'])

include: "rules/minisv_eval.smk"
minisv_eval = expand("output/minisv_puretumor_somatic_asm/{cell_line}_{platform}_{assembly}_count{cutoff}_eval.tsv", cell_line=celllines, platform=platforms, cutoff=[2,3,4,5,6,7], assembly=assembly)
minisv_eval_latest = expand("output/latest_minisv_puretumor_somatic_asm/{cell_line}_{platform}_{assembly}_count{cutoff}_eval.tsv", cell_line=celllines, platform=platforms, cutoff=[2,3,4,5,6,7], assembly=assembly)


rule all:
    input:
        genome_fa,
        rules.minimap2_workflow_all.input,
        sniffles_multi_files, sniffles_multi_vcf_files,
        clair3_outdir,
        rules.severus_workflow_all.input,
        rules.latest_severus_workflow_all.input,
        savana12_outdir, savana12_vcf, 
        minisv_pair, minisv_pair_tg, minisv_self, 
        minisv_eval,
        minisv_eval_latest,

        savana13_outdir, savana13_vcf,
        sniffles_multi_vcf_files_latest,

        ##sniffles_multi_files, 
        ##sniffles_mo_multi_files, sniffles_mo_multi_vcf_files,
        ##sniffles_mix, sniffles_mix_tbi,
        ##severus_outdir, 
        ##severus_single_outdir,
        ##severus_outdir_repeat2,
        nanomonsv_files, nanomonsv_files_latest
        ##extract_linear_files, extract_graph_files,
        ##svision_outdir, svision_vcfs, svision_outdir_somatic, svision_single_vcfs,
        ##minisv_pair, minisv_pair_t2t, minisv_pair_t2t_tg,
        ##minisv_self_extract,
        ##minisv_linear_def_extract, minisv_graph_def_extract, 
        ##minisv_single_call, minisv_single_graph_call, minisv_single_tg_call, minisv_single_tgs_call, minisv_single_lg_call,
        ##minisv_single_ts_call, minisv_single_s_call,
        ##paf_mixed, gaf_mixed, 
        ##minisv_mixed_mosaic_l, minisv_mixed_mosaic_g, minisv_mixed_mosaic_lg, minisv_mixed_mosaic_lt, minisv_mixed_mosaic_ltg,
        ##tn_eval_length, 
        ##single_eval_length, mixed_eval_length,  pair_eval_single_length,
        ##minisv_eval_files, minisv_eval_mixed_files, tn_eval_length,  minisv_eval_files_M,  minisv_pair_t, minisv_pair_g, minisv_pair_tg, minisv_pair_gx, minisv_pair_lx,
        ##single_eval_performance,
        ##"output/minisv_view_single/single_sample_allsvtools_svlength.tsv"
    default_target: True 
