#!/bin/bash -ex
/hlilab/alvin/miniconda3/envs/gafcall/bin/k8 /hlilab/alvin/miniconda3/envs/gafcall/bin/minisv.js annot -a -b ~/data/pangenome_sv_benchmarking/minisv/data/hs38.reg.bed -c 4 -l 100 -p ../1a.alignment_sv_tools/output/severus_latest_hifi1/COLO829_grch38_mixdown10_cutoff2_phased_mixed/all_SVs/severus_all.vcf ../1a.alignment_sv_tools/output/savana13/COLO829_hifi1/grch38/grch38_T_tag.classified.somatic.vcf ../1a.alignment_sv_tools/output/nanomonsv_latest/COLO829_hifi1/grch38_tnpair.vcf | awk '$9>=1' | cut -f 8 > output/minisv_mosaic_asm/COLO829_hifi1_grch38_severus_lowaf25_4.ids 

    minisv filterasm -c 4 -a -i output/minisv_mosaic_asm/COLO829_hifi1_grch38_severus_lowaf25_4.ids -b ~/data/pangenome_sv_benchmarking/minisv/data/hs38.reg.bed ../1a.alignment_sv_tools/output/severus_latest_hifi1/COLO829_grch38_mixdown10_cutoff2_phased_mixed/read_ids.csv ../10.mixed_assembly_10percent/output/align/COLO829_hifi1_asm.rsv.gz output/minisv_mosaic_asm/COLO829_hifi1_grch38_severus_lowaf25_4.asm_stat ../1a.alignment_sv_tools/output/severus_latest_hifi1/COLO829_grch38_mixdown10_cutoff2_phased_mixed/all_SVs/severus_all.vcf > output/minisv_mosaic_asm/COLO829_hifi1_grch38_severus_4_asm.vcf
#            minisv filterasm -r -c 4 -a -i output/minisv_mosaic_asm/COLO829_hifi1_grch38_severus_lowaf25_4.ids -b ~/data/pangenome_sv_benchmarking/minisv/data/hs38.reg.bed ../1a.alignment_sv_tools/output/severus_latest_hifi1/COLO829_grch38_mixdown10_cutoff2_phased_mixed/read_ids.csv ../10.mixed_assembly_10percent/output/align/COLO829_hifi1_asm.rsv.gz output/minisv_mosaic_asm/COLO829_hifi1_grch38_severus_lowaf25_4.asm_stat ../1a.alignment_sv_tools/output/severus_latest_hifi1/COLO829_grch38_mixdown10_cutoff2_phased_mixed/all_SVs/severus_all.vcf > output/minisv_mosaic_asm/COLO829_hifi1_grch38_severus_4_readname_asm.vcf
#
#            minisv filterasm -c 4 -a -b ~/data/pangenome_sv_benchmarking/minisv/data/hs38.reg.bed ../1a.alignment_sv_tools/output/sniffles_mosaic_latest/COLO829_hifi1/grch38_mixdown10_mosaic.vcf.gz ../10.mixed_assembly_10percent/output/align/COLO829_hifi1_asm.rsv.gz output/minisv_mosaic_asm/COLO829_hifi1_grch38_snf_4.asm_stat ../1a.alignment_sv_tools/output/sniffles_mosaic_latest/COLO829_hifi1/grch38_mixdown10_mosaic.vcf.gz > output/minisv_mosaic_asm/COLO829_hifi1_grch38_snf_lowaf25_4_asm.vcf
#            minisv filterasm -r -c 4 -a -b ~/data/pangenome_sv_benchmarking/minisv/data/hs38.reg.bed ../1a.alignment_sv_tools/output/sniffles_mosaic_latest/COLO829_hifi1/grch38_mixdown10_mosaic.vcf.gz ../10.mixed_assembly_10percent/output/align/COLO829_hifi1_asm.rsv.gz output/minisv_mosaic_asm/COLO829_hifi1_grch38_snf_4.asm_stat ../1a.alignment_sv_tools/output/sniffles_mosaic_latest/COLO829_hifi1/grch38_mixdown10_mosaic.vcf.gz > output/minisv_mosaic_asm/COLO829_hifi1_grch38_snf_lowaf25_4_readname_asm.vcf
#
#            minisv filterasm -c 4 -a -b ~/data/pangenome_sv_benchmarking/minisv/data/hs38.reg.bed ../10.mixed_assembly_10percent/output/minisv_mosaic_asm/COLO829_hifi1/grch38l_l+t+g_mosaic.msv.gz ../10.mixed_assembly_10percent/output/align/COLO829_hifi1_asm.rsv.gz output/minisv_mosaic_asm/COLO829_hifi1_grch38_msv_4_asm.stat ../10.mixed_assembly_10percent/output/minisv_mosaic_asm/COLO829_hifi1/grch38l_l+t+g_mosaic.msv.gz > output/minisv_mosaic_asm/COLO829_hifi1_grch38_msv_4_asm.vcf
#            minisv filterasm -r -c 4 -a -b ~/data/pangenome_sv_benchmarking/minisv/data/hs38.reg.bed ../10.mixed_assembly_10percent/output/minisv_mosaic_asm/COLO829_hifi1/grch38l_l+t+g_mosaic.msv.gz ../10.mixed_assembly_10percent/output/align/COLO829_hifi1_asm.rsv.gz output/minisv_mosaic_asm/COLO829_hifi1_grch38_msv_4_readname_asm.stat ../10.mixed_assembly_10percent/output/minisv_mosaic_asm/COLO829_hifi1/grch38l_l+t+g_mosaic.msv.gz > output/minisv_mosaic_asm/COLO829_hifi1_grch38_msv_4_readname_asm.vcf
#
#            minisv filterasm -c 4 -a -b ~/data/pangenome_sv_benchmarking/minisv/data/hs38.reg.bed ../10.mixed_assembly_10percent/output/minisv_mosaic_asm_new_g/COLO829_hifi1/grch38l_l+t+g_mosaic.msv.gz ../10.mixed_assembly_10percent/output/align/COLO829_hifi1_asm.rsv.gz output/minisv_mosaic_asm_new_g/COLO829_hifi1_grch38_msv_4_asm.stat ../10.mixed_assembly_10percent/output/minisv_mosaic_asm_new_g/COLO829_hifi1/grch38l_l+t+g_mosaic.msv.gz > output/minisv_mosaic_asm_new_g/COLO829_hifi1_grch38_msv_4_asm.vcf
#            minisv filterasm -r -c 4 -a -b ~/data/pangenome_sv_benchmarking/minisv/data/hs38.reg.bed ../10.mixed_assembly_10percent/output/minisv_mosaic_asm_new_g/COLO829_hifi1/grch38l_l+t+g_mosaic.msv.gz ../10.mixed_assembly_10percent/output/align/COLO829_hifi1_asm.rsv.gz output/minisv_mosaic_asm_new_g/COLO829_hifi1_grch38_msv_4_readname_asm.stat ../10.mixed_assembly_10percent/output/minisv_mosaic_asm_new_g/COLO829_hifi1/grch38l_l+t+g_mosaic.msv.gz > output/minisv_mosaic_asm_new_g/COLO829_hifi1_grch38_msv_4_readname_asm.vcf
#
#            bcftools filter -Oz -i 'FMT/VAF[0] <= 0.25' ../1a.alignment_sv_tools/output/severus_latest_hifi1/COLO829_grch38_mixdown10_cutoff2_phased_mixed/all_SVs/severus_all.vcf > output/minisv_mosaic_asm/COLO829_hifi1_grch38_severus_lowaf25_4.vcf.gz
#            bcftools filter -i 'FMT/VAF[0] <= 0.25' output/minisv_mosaic_asm/COLO829_hifi1_grch38_severus_4_asm.vcf > output/minisv_mosaic_asm/COLO829_hifi1_grch38_severus_lowaf25_4_asm.vcf
#            bcftools filter -i 'FMT/VAF[0] <= 0.25' output/minisv_mosaic_asm/COLO829_hifi1_grch38_severus_4_readname_asm.vcf > output/minisv_mosaic_asm/COLO829_hifi1_grch38_severus_lowaf25_4_readname_asm.vcf
#
#            if [ COLO829_hifi1 == 'COLO829_hifi1' ]; then
#                /hlilab/alvin/miniconda3/envs/gafcall/bin/k8 /hlilab/alvin/miniconda3/envs/gafcall/bin/minisv.js eval -c 4 -b ~/data/pangenome_sv_benchmarking/minisv/data/hs38.reg.bed /homes6/hli/hli1/gafcall/COLO829.truth.hs38.vcf ../10.mixed_assembly_10percent/output/minisv_mosaic_asm/COLO829_hifi1/grch38l_l+t+g_mosaic.msv.gz ../10.mixed_assembly_10percent/output/minisv_mosaic_asm/COLO829_hifi1/grch38l_l+t+g+s_mosaic.msv.gz ../10.mixed_assembly_10percent/output/minisv_mosaic_asm_new_g/COLO829_hifi1/grch38l_l+t+g_mosaic.msv.gz output/minisv_mosaic_asm/COLO829_hifi1_grch38_msv_4_asm.vcf ../1a.alignment_sv_tools/output/sniffles_mosaic_latest/COLO829_hifi1/grch38_mixdown10_mosaic.vcf.gz output/minisv_mosaic_asm/COLO829_hifi1_grch38_severus_lowaf25_4.vcf.gz output/minisv_mosaic_asm/COLO829_hifi1_grch38_severus_lowaf25_4_asm.vcf ../10.mixed_assembly_10percent/output/minisv_mosaic_asm/COLO829_hifi1/grch38l_l+t_mosaic.msv.gz ../10.mixed_assembly_10percent/output/minisv_mosaic_asm/COLO829_hifi1/grch38l_l+t+s_mosaic.msv.gz output/minisv_mosaic_asm/COLO829_hifi1_grch38_snf_lowaf25_4_asm.vcf output/minisv_mosaic_asm/COLO829_hifi1_grch38_snf_lowaf25_4_readname_asm.vcf output/minisv_mosaic_asm/COLO829_hifi1_grch38_severus_4_readname_asm.vcf output/minisv_mosaic_asm/COLO829_hifi1_grch38_severus_lowaf25_4_readname_asm.vcf output/minisv_mosaic_asm/COLO829_hifi1_grch38_msv_4_readname_asm.vcf output/minisv_mosaic_asm_new_g/COLO829_hifi1_grch38_msv_4_asm.vcf output/minisv_mosaic_asm_new_g/COLO829_hifi1_grch38_msv_4_readname_asm.vcf > output/minisv_mosaic_asm/COLO829_hifi1_grch38_count4_eval.tsv
#            else
#                for input in ../1a.alignment_sv_tools/output/sniffles_mosaic_latest/COLO829_hifi1/grch38_mixdown10_mosaic.vcf.gz ../10.mixed_assembly_10percent/output/minisv_mosaic_asm/COLO829_hifi1/grch38l_l+t+g+s_mosaic.msv.gz ../10.mixed_assembly_10percent/output/minisv_mosaic_asm/COLO829_hifi1/grch38l_l+t+g_mosaic.msv.gz output/minisv_mosaic_asm/COLO829_hifi1_grch38_msv_4_asm.vcf output/minisv_mosaic_asm/COLO829_hifi1_grch38_severus_lowaf25_4.vcf.gz output/minisv_mosaic_asm/COLO829_hifi1_grch38_severus_lowaf25_4_asm.vcf ../10.mixed_assembly_10percent/output/minisv_mosaic_asm/COLO829_hifi1/grch38l_l+t_mosaic.msv.gz ../10.mixed_assembly_10percent/output/minisv_mosaic_asm/COLO829_hifi1/grch38l_l+t+s_mosaic.msv.gz output/minisv_mosaic_asm/COLO829_hifi1_grch38_snf_lowaf25_4_asm.vcf output/minisv_mosaic_asm/COLO829_hifi1_grch38_severus_4_readname_asm.vcf output/minisv_mosaic_asm/COLO829_hifi1_grch38_severus_lowaf25_4_readname_asm.vcf output/minisv_mosaic_asm/COLO829_hifi1_grch38_snf_lowaf25_4_readname_asm.vcf output/minisv_mosaic_asm/COLO829_hifi1_grch38_msv_4_readname_asm.vcf; do
#                    /hlilab/alvin/miniconda3/envs/gafcall/bin/k8 /hlilab/alvin/miniconda3/envs/gafcall/bin/minisv.js eval -M -c 4 -b ~/data/pangenome_sv_benchmarking/minisv/data/hs38.reg.bed $input /homes6/hli/hli1/gafcall/COLO829.truth.hs38.vcf | head -2 >> output/minisv_mosaic_asm/COLO829_hifi1_grch38_count4_eval.tsv
#                done
#            fi
#
#            /hlilab/alvin/miniconda3/envs/gafcall/bin/k8 /hlilab/alvin/miniconda3/envs/gafcall/bin/minisv.js union -c 4 -b ~/data/pangenome_sv_benchmarking/minisv/data/hs38.reg.bed output/minisv_mosaic_asm/COLO829_hifi1_grch38_severus_lowaf25_4.vcf.gz ../10.mixed_assembly_10percent/output/minisv_mosaic_asm/COLO829_hifi1/grch38l_l+t+g_mosaic.msv.gz ../1a.alignment_sv_tools/output/sniffles_mosaic_latest/COLO829_hifi1/grch38_mixdown10_mosaic.vcf.gz > output/minisv_mosaic_asm/origunion_COLO829_hifi1_somatic_generation4_eval.tsv
#
#            /hlilab/alvin/miniconda3/envs/gafcall/bin/k8 /hlilab/alvin/miniconda3/envs/gafcall/bin/minisv.js union -c 4 -b ~/data/pangenome_sv_benchmarking/minisv/data/hs38.reg.bed output/minisv_mosaic_asm/COLO829_hifi1_grch38_severus_lowaf25_4_asm.vcf output/minisv_mosaic_asm/COLO829_hifi1_grch38_msv_4_asm.vcf output/minisv_mosaic_asm/COLO829_hifi1_grch38_snf_lowaf25_4_asm.vcf > output/minisv_mosaic_asm/asmunion_COLO829_hifi1_somatic_generation4_eval.tsv
#
