import os
import glob
import sys
import pandas as pd
from snakemake.utils import validate

configfile: "config.yaml"

clair3_outdir  = expand("output/clair3/{cell_line}/{assembly}/", cell_line=config['samples']['normal'], assembly=config['assembly'])
sniffles_files  = expand("output/sniffles/{cell_line}/{assembly}.vcf.gz", cell_line=config['samples']['normal'], assembly=config['assembly'])
sniffles_tbi_files  = expand("output/sniffles/{cell_line}/{assembly}.vcf.gz.tbi", cell_line=config['samples']['normal'], assembly=config['assembly'])
sniffles_mo_files  = expand("output/sniffles_mosaic/{cell_line}/{assembly}.vcf.gz", cell_line=config['samples']['normal'], assembly=config['assembly'])
sniffles_mo_tbi_files  = expand("output/sniffles_mosaic/{cell_line}/{assembly}.vcf.gz.tbi", cell_line=config['samples']['normal'], assembly=config['assembly'])
cutesv_files  = expand("output/cutesv/{cell_line}/{assembly}.vcf.gz", cell_line=config['samples']['normal'], assembly=config['assembly'])
cutesv_files_cutoff2  = expand("output/cutesv/{cell_line}_cutoff2/{assembly}.vcf.gz", cell_line=config['samples']['normal'], assembly=config['assembly'])

svision_files  = expand("output/svision/{cell_line}/{assembly}/{cell_line}.svision_pro_v1.8.s5.vcf", cell_line=config['samples']['normal'], assembly=config['assembly'])

hp_tag_files = expand("output/extract_hp/{cell_line}_{assembly}.tsv.gz", cell_line=config['samples']['normal'], assembly=config['assembly'])


wildcard_constraints:
    cell_line = "[A-Za-z0-9]+",
    assembly = "chm13|grch38",

module aligner_workflow:
    snakefile: "rules/minimap2.smk"
    config: config

use rule * from aligner_workflow as minimap2_workflow_*

include: "rules/sniffles2.smk"

include: "rules/clair3.smk"

module severus_workflow:
    snakefile: "rules/severus.smk"
    config: config

use rule * from severus_workflow as severus_workflow_*

include: "rules/cutesv.smk"
include: "rules/cutesv_cutoffs.smk"
include: "rules/svision.smk"

rule all:
    input:
        rules.minimap2_workflow_all.input,
        rules.severus_workflow_all.input,
        sniffles_files, sniffles_tbi_files,
        cutesv_files, sniffles_mo_files, sniffles_mo_tbi_files, svision_files, hp_tag_files,
        cutesv_files_cutoff2
    default_target: True 
