import os
import glob
import sys
import pandas as pd
from snakemake.utils import validate

configfile: "config.yaml"

sniffles_files  = expand(expand("output/sniffles/{cell_line}_{platform}/{{pair}}/{{assembly}}.vcf.gz", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), pair=["T", "BL"], assembly=config['assembly'])
sniffles_tbi_files  = expand(expand("output/sniffles/{cell_line}_{platform}/{{pair}}/{{assembly}}.vcf.gz.tbi", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), pair=["T", "BL"], assembly=config['assembly'])
clair3_outdir  = expand(expand("output/clair3/{cell_line}_{platform}/{{pair}}/{{assembly}}/", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), pair=["T", "BL"], assembly=config['assembly'])
savana_outdir  = expand(expand("output/savana/{cell_line}_{platform}/{{assembly}}", zip, cell_line=config['samples']['tumor'], platform=config['samples']['platform']), assembly=config['assembly'])


wildcard_constraints:
    cell_line = "[A-Za-z0-9]+",
    pair = "BL|T",
    assembly = "chm13"

module aligner_workflow:
    snakefile: "rules/minimap2.smk"
    config: config

use rule * from aligner_workflow as minimap2_workflow_*

include: "rules/sniffles2.smk"
include: "rules/savana.smk"
include: "rules/clair3.smk"

rule all:
    input:
        rules.minimap2_workflow_all.input,
        sniffles_files, sniffles_tbi_files,
        savana_outdir, clair3_outdir
    default_target: True 
